#include <iostream>
#include <exception>
#include <signal.h>

using namespace std;

int main()
{
    try
    {
        throw 20;
    }
    catch (...)
    {
        cerr << "Caught an exception" << endl;
    }

    try
    {
        throw runtime_error("Specific exception");
    }
    catch (exception &e)
    {
        cerr << "Caught runtime error: " << e.what() << endl;
    }

    return 0;
}
